import {
  FaRobot,
  FaCoins,
  FaChartLine,
  FaShieldAlt,
} from "react-icons/fa";

import { FaArrowTrendUp } from "react-icons/fa6";
function AIDecisions() {
  const decisions = [
    {
      asset: "Bitcoin",
      action: "BUY",
      confidence: "91%",
      reason: "Bullish momentum with ETF inflows.",
      color: "green",
    },
    {
      asset: "Gold",
      action: "HOLD",
      confidence: "88%",
      reason: "Stable safe-haven demand.",
      color: "yellow",
    },
    {
      asset: "Silver",
      action: "BUY",
      confidence: "86%",
      reason: "Industrial demand increasing.",
      color: "green",
    },
    {
      asset: "Stocks",
      action: "BUY",
      confidence: "93%",
      reason: "Strong earnings season expected.",
      color: "green",
    },
  ];

  return (
    <div className="p-10 bg-slate-100 min-h-screen">

      <div className="flex items-center gap-4 mb-8">

        <FaRobot className="text-5xl text-cyan-600" />

        <div>

          <h1 className="text-4xl font-bold">

            AI Decisions

          </h1>

          <p className="text-gray-500">

            Latest recommendations generated by FinPilot AI

          </p>

        </div>

      </div>

      <div className="grid lg:grid-cols-2 gap-8">

        {decisions.map((item, index) => (

          <div
            key={index}
            className="bg-white rounded-3xl shadow-lg p-8"
          >

            <div className="flex justify-between items-center">

              <div>

                <h2 className="text-3xl font-bold">

                  {item.asset}

                </h2>

                <p className="text-gray-500 mt-2">

                  {item.reason}

                </p>

              </div>

              <FaCoins className="text-5xl text-cyan-500" />

            </div>

            <div className="grid grid-cols-3 gap-5 mt-8">

              <div className="bg-slate-100 rounded-2xl p-4">

                <FaChartLine className="text-green-500 text-2xl mb-3" />

                <h3 className="text-sm text-gray-500">

                  Recommendation

                </h3>

                <h1 className="text-2xl font-bold">

                  {item.action}

                </h1>

              </div>

              <div className="bg-slate-100 rounded-2xl p-4">

                <FaShieldAlt className="text-blue-500 text-2xl mb-3"/>

                <h3 className="text-sm text-gray-500">

                  Confidence

                </h3>

                <h1 className="text-2xl font-bold">

                  {item.confidence}

                </h1>

              </div>

              <div className="bg-slate-100 rounded-2xl p-4">

                <FaChartLine className="text-purple-500 text-2xl mb-3"/>

                <h3 className="text-sm text-gray-500">

                  Trend

                </h3>

                <h1 className="text-2xl font-bold">

                  Bullish

                </h1>

              </div>

            </div>

          </div>

        ))}

      </div>

    </div>
  );
}

export default AIDecisions;